apiVersion: apps/v1
kind: StatefulSet # Changed from Deployment
metadata:
  name: postgresql
spec:
  terminationGracePeriodSeconds: 10
  serviceName: "postgresql" # Mandatory for StatefulSets: headless service name
  replicas: 1 # Typically 1 for a single PostgreSQL instance
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - image: postgres:14
        name: postgresql
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi" # Corrected: "512Gi" is likely a typo for "512Mi" or much too large
            cpu: "500m"
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: pg-configmap
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: pg-configmap
              key: POSTGRES_DB
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata      
        ports:
        - containerPort: 5432
          name: postgresql
        volumeMounts:
        - name: postgresql-data # This references the volumeClaimTemplates below
          mountPath: /var/lib/postgresql/data
          subPath: pgdata # RECOMMENDED: Mount a subdirectory to avoid lost+found issues
  volumeClaimTemplates: # Replaces the 'volumes' section for dynamic PVCs
  - metadata:
      name: postgresql-data # Must match the volumeMounts.name
    spec:
      accessModes: [ "ReadWriteOnce" ] # Single Pod access for a primary database
      resources:
        requests:
          storage: 5Gi # Request a suitable storage size
      storageClassName: ebs-sc # Uncomment if you have a specific StorageClass
