apiVersion: v1
kind: Service
metadata:
  name: hotel-service
spec:
  selector:
    app: hotel-service
  type: ClusterIP
  ports:
  - name: hote-service-port
    protocol: TCP
    port: 8082
    targetPort: 8082
 