apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgresql
  type: ClusterIP
  ports:
  - name: pg-port
    protocol: TCP
    port: 5432
    targetPort: 5432
